version: "3"
 
services:
  coordinator:
    build: ./coordinator
    ports:
      - 5000:80

  worker:
    build: ./worker
    ports:
      - 3141:3141
    depends_on:
      - coordinator
    deploy:
      mode: replicated
      replicas: 50

      resources:
        # Hard limit - Docker does not allow to allocate more
        limits:
          cpus: '0.25'
          memory: 512M
 